<?php
add_action('admin_footer', function() {
	if(get_post() == null || get_post()->post_type != 'flight') return;
	?>
	<script type="text/javascript">
        let title = document.getElementById('title');
        title.setAttribute('readonly', true);
        title.placeholder = '<?php echo __('Autogenerated', 'airport_flights') ?>';
        document.getElementById('title-prompt-text').innerHTML = '';

        jQuery(document).ready(function ($) {
            $('#publish').click(function(){
                let $scope = $('#airline-all > ul');

                if ($scope.find('input:checked').length < 1) {
                    alert('<?php echo __('Airline is required', 'airport_flights') ?>');
                    return false;
                }
                if ($scope.find('input:checked').length > 1) {
                    alert('<?php echo __('Only one airline can be selected ', 'airport_flights') ?>');
                    return false;
                }

                let $gate = $('#gate-all > ul');
                if ($gate.find('input:checked').length < 1) {
                    alert('<?php echo __('Gate is required', 'airport_flights') ?>');
                    return false;
                }
                if ($gate.find('input:checked').length > 1) {
                    alert('<?php echo __('Only one gate can be selected ', 'airport_flights') ?>');
                    return false;
                }

                let $status = $('#status-all > ul');
                if ($status.find('input:checked').length < 1) {
                    alert('<?php echo __('Status is required', 'airport_flights') ?>');
                    return false;
                }
                if ($status.find('input:checked').length > 1) {
                    alert('<?php echo __('Only one status can be selected ', 'airport_flights') ?>');
                    return false;
                }


                title.value = `<?php echo __('Code', 'airport_flights') ?>: ${flight_app.flight_code}, <?php echo __('Type', 'airport_flights') ?>: ${flight_app.currentType} `
            });
        });
	</script>
	<?php
});