<?php
add_action('admin_footer', function() {
	if(get_post() == null || get_post()->post_type != 'flight') return;
	?>
	<script type="text/javascript">
        let title = document.getElementById('title');
        title.setAttribute('readonly', true);
        title.placeholder = '<?php echo __('Autogenerated') ?>';
        document.getElementById('title-prompt-text').innerHTML = '';

        jQuery(document).ready(function ($) {
            $('#publish').click(function(){
                let $scope = $('#airline-all > ul');

                if ($scope.find('input:checked').length < 1) {
                    alert('<?php echo __('Airline is required', 'Airline is required') ?>');
                    return false;
                }
                if ($scope.find('input:checked').length > 1) {
                    alert('<?php echo __('Only one airline can be selected ', 'Only one airline can be selected ') ?>');
                    return false;
                }

                let $door = $('#door-all > ul');
                if ($door.find('input:checked').length < 1) {
                    alert('<?php echo __('Door is required', 'Door is required') ?>');
                    return false;
                }
                if ($door.find('input:checked').length > 1) {
                    alert('<?php echo __('Only one door can be selected ', 'Only one door can be selected ') ?>');
                    return false;
                }

                let $status = $('#status-all > ul');
                if ($status.find('input:checked').length < 1) {
                    alert('<?php echo __('Status is required', 'Status is required') ?>');
                    return false;
                }
                if ($status.find('input:checked').length > 1) {
                    alert('<?php echo __('Only one status can be selected ', 'Only one status can be selected ') ?>');
                    return false;
                }


                title.value = `<?php echo __('Code') ?>: ${flight_app.flight_code}, <?php echo __('Type') ?>: ${flight_app.currentType} `
            });
        });
	</script>
	<?php
});